#!/usr/bin/env python3
"""Turn cards.json into 0008_geological_assistant_seed.sql (idempotent upserts).
Run: python3 gen_seed.py  (reads ./cards.json, writes ./0008_geological_assistant_seed.sql)"""
import json, collections
D = json.load(open('cards.json'))
COURSE = 'geological-assistant'
q = lambda s: "'" + str(s).replace("'", "''") + "'"
null = lambda s: 'null' if s in (None, '') else q(s)
freq = {'h': 3, 'm': 2, 'l': 1}
tier = {'h': 1, 'm': 2, 'l': 3}
out = ["-- Generated by gen_seed.py from cards.json. Safe to re-run (upserts).", "begin;"]
for n, name in sorted(D['units'].items(), key=lambda x: int(x[0])):
    out.append(f"insert into public.modules (id,course_id,module_no,name,marks) values "
               f"({q(f'{COURSE}-m{n}')},{q(COURSE)},{n},{q(name)},20) "
               f"on conflict (id) do update set name=excluded.name;")
facts = [c for c in D['cards'] if c['k'] == 'f']
qs = [c for c in D['cards'] if c['k'] == 'q']
byt = collections.defaultdict(list)
for i, c in enumerate(facts):
    cid = f"{COURSE}-{c['id']}"
    byt[(c['u'], c['t'])].append(cid)
    out.append(
        "insert into public.cards (id,course_id,module_id,subtopic,statement,reasoning,source_ref,"
        "verified,frequency,tier,order_index) values "
        f"({q(cid)},{q(COURSE)},{q(f'{COURSE}-m{c['u']}')},{q(c['t'])},{q(c['a'])},{null(c.get('w'))},"
        f"{null('; '.join(c.get('p', [])))},{'true' if c.get('c', 0) == 0 else 'false'},"
        f"{freq[c['f']]},{tier[c['f']]},{i}) on conflict (id) do update set "
        "statement=excluded.statement,reasoning=excluded.reasoning,source_ref=excluded.source_ref,"
        "verified=excluded.verified,frequency=excluded.frequency,tier=excluded.tier;")
L = 'abcd'
for c in qs:
    qid = f"{COURSE}-{c['id']}"
    o = c['o']; a = L[c['x']]
    out.append(
        "insert into public.questions (id,course_id,paper_code,stem,option_a,option_b,option_c,option_d,"
        "official_answer,verified_answer) values "
        f"({q(qid)},{q(COURSE)},{null('; '.join(c.get('p', [])))},{q(c['q'])},{q(o[0])},{q(o[1])},{q(o[2])},{q(o[3])},{q(a)},{q(a)}) "
        "on conflict (id) do update set stem=excluded.stem,option_a=excluded.option_a,option_b=excluded.option_b,"
        "option_c=excluded.option_c,option_d=excluded.option_d,official_answer=excluded.official_answer,"
        "verified_answer=excluded.verified_answer;")
    for cid in byt.get((c['u'], c['t']), [])[:3]:
        out.append(f"insert into public.question_cards (question_id,card_id) values ({q(qid)},{q(cid)}) on conflict do nothing;")
out.append("commit;")
open('0008_geological_assistant_seed.sql', 'w').write("\n".join(out) + "\n")
print(len(facts), 'cards', len(qs), 'questions')
