/**
 * Store-listing metadata for the mobile apps we publish.
 *
 * Google Play and the App Store each require a privacy policy URL, a support
 * URL, and — for anything with accounts — a way to request deletion that works
 * without installing the app. Those pages are generated from this file so the
 * disclosures cannot drift from what an app actually collects, and so adding
 * the production builds later is a data change rather than four new pages.
 */

export type DataCategory = {
  /** Matches Play's Data safety vocabulary, so the console form can be filled from this. */
  category: string;
  items: string[];
  purpose: string;
  /** Play asks this per data type. */
  optional?: boolean;
};

/** A section of an app-specific terms of service. */
export type TermsSection = { heading: string; body: string[] };

export type AppTerms = {
  updated: string;
  intro: string;
  sections: TermsSection[];
};

export type AppEntry = {
  slug: string;
  name: string;
  tagline: string;
  androidPackage: string;
  iosBundleId: string;
  audience: string;
  isDemo: boolean;
  summary: string;
  collects: DataCategory[];
  permissions: { name: string; why: string }[];
  sharedWith: string[];
  /** Keys into PROCESSORS. */
  processors: string[];
  retention: string;
  /** Personal data about people who are not the app's user. */
  thirdPartyData?: string;

  /**
   * Plain description of what the app does, for the overview page. Falls back
   * to the privacy purposes when absent — those read as disclosures rather
   * than features, so a consumer-facing app should set this.
   */
  features?: string[];
  /** Square icon shown in the overview hero. */
  iconSrc?: string;
  /** Extra line in the Availability section — store status, how to get it. */
  availabilityNote?: string;
  /**
   * A scannable link to this app's page, offered for download so it can be
   * printed or forwarded. Generated by scripts/build-qr.mjs.
   */
  qr?: { svg: string; png: string; target: string };
  /** Date the app's own disclosures last changed. */
  policyUpdated: string;
  /** How the privacy page names the backend the app talks to. */
  serviceName: string;
  /** The lawful basis on which we hold the data. */
  lawfulBasis: string;
  /** Sign-in troubleshooting, for the support page. */
  signInHelp: string;
  /** The app-specific sentence closing the Security section. */
  securityNote: string;
  /** What the user should quote so we can find their account for deletion. */
  deleteIdentifier: string;
  /** What deleting the account removes. */
  deletes: string[];
  /** What survives deletion, and why. Supports **bold**. */
  retainsOnDelete: string;
  /** Overrides DEFAULT_NOT_COLLECTED where an app's hardware use differs. */
  notCollected?: string[];
  /** App-specific terms. Apps without this simply have no terms page. */
  terms?: AppTerms;
};

/**
 * The baseline "what we do not collect" list. An app that uses different
 * hardware — or none — overrides it via `notCollected`.
 */
export const DEFAULT_NOT_COLLECTED = [
  "We do not collect your contacts, calendar, call logs or SMS.",
  "We do not track you across other apps or websites.",
  "We do not use advertising identifiers and show no advertising.",
  "We do not record audio or use the camera except at the moment you tap to capture something.",
  "We never receive your Google password, and — where the app takes payments — never your card, UPI or netbanking credentials.",
];

const SUPPORT_EMAIL = "info@calecutech.com";
const COMPANY = "Calecute Technologies LLC";

export const CONTACT = {
  email: SUPPORT_EMAIL,
  company: COMPANY,
  address: "Kozhikode (Calicut), Kerala, India",
  /** Named contact for grievances, as India's DPDP Act 2023 expects. */
  grievanceOfficer: "The Grievance Officer",
};

/** Named services that receive data, which Google asks to see disclosed. */
export type Processor = { name: string; role: string; policy: string };

export const PROCESSORS: Record<string, Processor[]> = {
  google: [
    {
      name: "Google Sign-In",
      role: "Authenticates you and tells us your name, email address and profile picture. We never see your Google password.",
      policy: "https://policies.google.com/privacy",
    },
  ],
  razorpay: [
    {
      name: "Razorpay Software Private Limited",
      role: "Processes deposit payments. Card, UPI and netbanking details are entered on Razorpay's own screen and are never sent to or stored on our servers.",
      policy: "https://razorpay.com/privacy/",
    },
  ],
  razorpay_recallio: [
    {
      name: "Razorpay Software Private Limited",
      role: "Takes payment when you choose to pay by UPI or card. The payment screen is Razorpay's own; your UPI id, card or netbanking details are entered there and never reach us. We are told only that a payment succeeded, and for how much.",
      policy: "https://razorpay.com/privacy/",
    },
  ],
  fcm: [
    {
      name: "Firebase Cloud Messaging (Google LLC)",
      role: "Delivers push notifications to your device. It receives the notification text and your device's push token. It is not used to sign you in and holds none of your app data.",
      policy: "https://firebase.google.com/support/privacy",
    },
  ],
  supabase: [
    {
      name: "Supabase Inc.",
      role: "Hosts the database and the sign-in service. Your study record is stored there so a new phone can pick up where the old one left off. Supabase stores it on our behalf and does not use it for its own purposes.",
      policy: "https://supabase.com/privacy",
    },
  ],
  play_billing: [
    {
      name: "Google Play Billing (Google LLC)",
      role: "Takes the payment for a subscription and tells the app whether you have one. The payment screen is Google's own — your card, UPI or netbanking details are entered there and never reach us. We receive only the fact that a subscription is active.",
      policy: "https://policies.google.com/privacy",
    },
  ],
  hosting: [
    {
      name: "Vercel Inc. and Neon Inc.",
      role: "Host the application and its database. They store data on our behalf and do not use it for their own purposes.",
      policy: "https://vercel.com/legal/privacy-policy",
    },
  ],
};

const BASE: Omit<AppEntry, 'slug'|'name'|'androidPackage'|'iosBundleId'|'isDemo'>[] = [
  {
    tagline: "Field officer asset capture for SARFAESI possession",
    audience:
      "Authorised officers and field officers of a lending institution. Access requires credentials issued by that institution.",
    summary:
      "Sarfez Field is used by a bank's authorised officers to record a site visit under the SARFAESI Act — the schedule of property, a GPS pin, the statutory photograph set, the movable inventory, and a panchnama signed by two witnesses.",
    collects: [
      {
        category: "Location",
        items: ["Precise location (GPS coordinates and accuracy)"],
        purpose:
          "The coordinates of the secured asset are recorded as evidence of where the visit took place. Location is captured only when the officer taps to capture it — never in the background.",
      },
      {
        category: "Photos and videos",
        items: [
          "Photographs of the property",
          "Video of the possession proceedings",
          "Handwritten signature images",
        ],
        purpose:
          "Evidence annexed to the possession panchnama. Each file is stamped server-side with the capture time and the officer's identity.",
      },
      {
        category: "Personal identifiers",
        items: [
          "Officer name, employee ID, branch, and mobile number",
          "Witness name, parent's or spouse's name, address, age, occupation, and phone number",
        ],
        purpose:
          "Identifying the officer conducting the visit, and the two independent witnesses the possession procedure requires.",
      },
      {
        category: "App activity",
        items: ["Notes and observations typed by the officer", "Task status"],
        purpose: "The officer's remarks form part of the panchnama record.",
      },
      {
        category: "Device identifiers",
        items: ["Push notification token"],
        purpose: "Delivering task assignments and review outcomes.",
        optional: true,
      },
    ],
    permissions: [
      {
        name: "Camera",
        why: "Photographing the property and the affixed possession notice. Used only when the officer taps a capture tile.",
      },
      {
        name: "Precise location",
        why: "Recording the coordinates of the secured asset. Foreground only; the app has no background location access.",
      },
      {
        name: "Photos and media",
        why: "Attaching an existing photograph when the camera is unavailable.",
      },
      { name: "Internet", why: "Syncing captured reports to the bank's system." },
    ],
    sharedWith: [
      "The lending institution that employs the officer and assigned the visit. The data is captured on that institution's behalf and is visible to its reviewing officers.",
    ],
    processors: ["hosting"],
    retention:
      "Captured reports are retained by the lending institution under its own record-retention policy, because possession records are statutory documents. We do not retain them independently of that institution.",
    thirdPartyData:
      "This app records personal data about people who are not its users — principally the two panchnama witnesses, and the borrower named on the case. That data is collected by the officer, on behalf of the lending institution, for a statutory purpose under the SARFAESI Act. The institution is the data fiduciary for it; we process it on their instructions. Requests about that data should be directed to the institution, and we will assist them in responding.",
    policyUpdated: "September 4, 2026",
    serviceName: "the Sarfez service",
    lawfulBasis:
      "We process this data on the instructions of the lending institution that assigned the visit, so that it can discharge obligations placed on it by the SARFAESI Act, 2002. That institution is the data fiduciary; we are its processor.",
    signInHelp:
      "Credentials are issued by the bank you work for, not by us. If you cannot sign in, contact your branch IT helpdesk first — we cannot create or reset officer accounts.",
    securityNote: "An officer or buyer can only reach records belonging to them.",
    deleteIdentifier: "the mobile number or employee ID you sign in with",
    deletes: [
      "Your officer profile, contact details, and preferences",
      "Your sign-in credentials and any active sessions",
      "Your push notification token",
    ],
    retainsOnDelete:
      "Possession reports you submitted are **not** deleted. They are statutory records belonging to the lending institution that assigned the visit, not to us — a possession panchnama cannot be withdrawn because the officer who recorded it left. Your name stays attached to them as the recording officer. Requests about those records go to that institution.",
  },
  {
    tagline: "Discover and act on bank auction properties",
    audience: "Members of the public interested in bank auction properties.",
    summary:
      "Sarfez Auctions lets a prospective buyer search properties a bank has put up for auction, save and track them, register interest, and complete the earnest money deposit required to bid.",
    collects: [
      {
        category: "Personal identifiers",
        items: [
          "Name",
          "Mobile number",
          "Email address and Google profile picture, if you sign in with Google",
        ],
        purpose: "Creating and securing your account.",
      },
      {
        category: "Financial information",
        items: [
          "PAN (Permanent Account Number)",
          "Bank account number, IFSC, and account holder name, for refunds",
          "Earnest money deposit records",
        ],
        purpose:
          "PAN and a refund account are required before an earnest money deposit can be accepted, and are how a deposit is returned to an unsuccessful bidder. Card and UPI details are entered on the payment provider's own screen and never reach our servers.",
      },
      {
        category: "Location",
        items: ["Approximate location"],
        purpose:
          "Sorting listings by distance from you. Optional — declining it only removes the distance sort.",
        optional: true,
      },
      {
        category: "App activity",
        items: [
          "Saved listings and saved searches",
          "Site visit requests and expressions of interest",
        ],
        purpose: "Providing the features you asked for and alerting you to matches.",
      },
      {
        category: "Device identifiers",
        items: ["Push notification token"],
        purpose: "Alerting you to auction dates and deposit deadlines.",
        optional: true,
      },
    ],
    permissions: [
      {
        name: "Approximate location",
        why: "Sorting listings by distance. Optional — the app works fully without it.",
      },
      { name: "Internet", why: "Loading listings and submitting your requests." },
    ],
    sharedWith: [
      "The lending institution running an auction you register for, so it can verify your eligibility to bid.",
      "Our payment provider, which processes the deposit. Card and UPI details are handled entirely by that provider.",
    ],
    processors: ["google", "razorpay", "hosting"],
    retention:
      "Account data is kept while your account exists. Deposit and refund records are kept for as long as tax and financial-record rules require, which is longer than the account itself, and is why deleting an account does not delete those records.",
    policyUpdated: "September 4, 2026",
    serviceName: "the Sarfez service",
    lawfulBasis:
      "We process your data to provide the service you asked for — searching listings, registering interest, and completing a deposit — and, for deposit and refund records, to meet obligations under Indian financial and tax law. You give consent when you create an account, and you may withdraw it by deleting the account.",
    signInHelp:
      "Sign in with your mobile number or a Google account. If a one-time code does not arrive, check the number and try again after a minute.",
    securityNote: "An officer or buyer can only reach records belonging to them.",
    deleteIdentifier: "the mobile number or employee ID you sign in with",
    deletes: [
      "Your name, phone number, email, and Google profile data",
      "Your PAN and refund account details",
      "Saved listings, saved searches, and alerts",
      "Site visit requests and expressions of interest",
      "Your push notification token and any active sessions",
    ],
    retainsOnDelete:
      "Records of any earnest money deposit you paid or had refunded are **not** deleted. Financial and tax law requires them to be retained, and the bank running the auction needs them to show who was eligible to bid. They are kept for the period the law requires and then removed.",
  },
  {
    tagline: "Calculators, JAIIB and CAIIB notes, and a circle scoped to your own bank",
    audience:
      "Employees of Indian banks — public sector, private, regional rural, co-operative, small finance and payments banks, and the regulators and development finance institutions. Anyone may install it; the community features require you to identify the bank you work at.",
    summary:
      "BankMates gives bank staff a set of financial calculators that run entirely on the phone, study material for the IIBF's JAIIB and CAIIB certifications, and a question-and-answer space that is visible only to colleagues at the same bank.",
    collects: [
      {
        category: "Personal identifiers",
        items: [
          "Name, email address and profile picture, from Google Sign-In",
        ],
        purpose:
          "Creating your account and showing colleagues who wrote a post. We never see your Google password.",
      },
      {
        category: "Personal identifiers",
        items: [
          "The bank you work at",
          "Branch or office, designation, and grade or scale",
        ],
        purpose:
          "The bank you choose decides which colleagues you can see and who can see you — it is the boundary the whole community sits inside. Grade decides whether you can post Tips. Branch, designation and grade are optional and you can leave them blank.",
      },
      {
        category: "Messages and other user-generated content",
        items: [
          "Doubts you ask and replies you write",
          "Tips you post, and the tips you like",
          "Messages you send to colleagues at your bank",
          "Reports you file about someone else's post",
        ],
        purpose:
          "Showing your posts to colleagues at your bank, and reviewing anything that gets reported. Please do not put customer information, account numbers or anything your bank treats as confidential into a post — this is a staffroom, not a banking system.",
      },
      {
        category: "Personal identifiers",
        items: ["Email addresses of colleagues you invite"],
        purpose:
          "Sending a single invitation and recording whether it was accepted, so your referral count is accurate. See the section below on people who do not use the app.",
        optional: true,
      },
      {
        category: "App activity",
        items: [
          "Which coaching chapters you have opened and marked as read",
          "Which calculator you opened, and when",
        ],
        purpose:
          "Showing your reading progress, and telling us which calculators are worth improving. The numbers you type into a calculator are never part of this — see below.",
        optional: true,
      },
      {
        category: "Device identifiers",
        items: ["Push notification token"],
        purpose:
          "Delivering a notification when someone answers your doubt, a tip is posted at your bank, or a colleague joins through your invitation.",
        optional: true,
      },
    ],
    permissions: [
      {
        name: "Internet",
        why: "Signing in, and loading coaching content and your bank's doubts and tips. The calculators need no connection at all.",
      },
      {
        name: "Notifications",
        why: "Telling you about replies, new tips and accepted invitations. Optional — declining it costs you nothing but the alerts.",
      },
    ],
    sharedWith: [
      "Other BankMates users who have identified themselves as working at the same bank as you. They see your name, profile picture, branch, designation and grade, and anything you post. Nobody at a different bank can see any of it — every request for a doubt, a tip or a message is filtered by your bank on our servers, and the app has no way to ask for another bank's content.",
      "Nobody else. We do not share your data with your employer as an organisation, and identifying your bank does not give it access to your account or your posts.",
    ],
    processors: ["google", "fcm", "hosting"],
    retention:
      "Your account and its content are kept while the account exists. A post you delete is hidden immediately and removed within 30 days; we keep it briefly so a report filed against it can still be reviewed. Invitation records are kept while your account exists, because they are what your referral count is computed from.",
    thirdPartyData:
      "When you invite a colleague by email, you give us that person's address. We use it once, to send a single invitation naming you as the sender, and we record whether it was accepted. We never send a reminder, never add the address to a mailing list, and never share it. If someone does not accept, their address is removed when you delete your account, and sooner on request to the address below. Only invite people you actually know and who would expect to hear from you.",
    iconSrc: "/bankmates/icon.png",
    availabilityNote:
      "BankMates is not on Google Play yet — the first internal-testing build is on its way, and this page will carry the store link when the listing goes live. The QR code above already points here, so anything printed now keeps working afterwards.",
    qr: {
      svg: "/bankmates/qr.svg",
      png: "/bankmates/qr.png",
      target: "https://calecutech.com/apps/bankmates",
    },
    features: [
      "Five financial calculators built for how bank books actually work: a two-phase staff loan with a separate interest account, SIP, FD and RD on the quarterly-compounding convention Indian banks use, reducing-balance EMI with a full amortisation schedule, and a SARFAESI notice timeline.",
      "Every calculator runs entirely on the phone. They work with no signal, and the figures you type never leave the device.",
      "Study material for the IIBF's JAIIB and CAIIB certifications, organised by paper, module and chapter, with end-of-chapter self-checks. Anything you open is cached for reading offline.",
      "A question-and-answer space visible only to colleagues at the same bank you identified, plus tips posted by officers.",
      "Invite colleagues by email or WhatsApp, and see how many joined through you.",
    ],
    policyUpdated: "September 6, 2026",
    serviceName: "the BankMates service",
    lawfulBasis:
      "We process your data to provide the service you asked for — an account, your bank's doubts and tips, and your coaching progress. You give consent when you create an account, and you may withdraw it at any time by deleting the account. We rely on the same consent for invitations you choose to send.",
    signInHelp:
      "BankMates uses Google Sign-In only. If sign-in fails, check that the Google account has a verified email address — we cannot create an account without one. We cannot reset a Google password; that is done at myaccount.google.com. Your bank is set once during sign-up and can only be changed by writing to us, because your posts live inside that bank's circle.",
    securityNote:
      "Doubts, tips and messages are filtered by your bank on the server, not in the app, so a device cannot request another bank's content even if it is tampered with. Sign-in tokens are held in the device keychain or Android keystore, never in ordinary app storage.",
    deleteIdentifier: "the Google account you sign in with",
    deletes: [
      "Your name, email address, profile picture, and the bank, branch, designation and grade on your profile",
      "The doubts, replies and tips you posted, and your likes",
      "Messages you sent to colleagues",
      "Your coaching progress and calculator usage records",
      "Invitations you sent that were never accepted",
      "Your push notification token and any active sessions",
    ],
    retainsOnDelete:
      "Where a colleague already replied to a doubt you asked, the thread is **not** removed wholesale — your question is anonymised rather than deleted, so their answer does not lose its context for everyone else at your bank. Nothing identifying you remains attached to it. Records of invitations that were accepted are kept in a form that no longer names the person invited, because another user's referral count depends on them.",
    notCollected: [
      "We do not collect your contacts, calendar, call logs or SMS.",
      "We do not track you across other apps or websites.",
      "We do not use advertising identifiers and show no advertising.",
      "The app never asks for camera, microphone, location or file access, because it does not use them.",
      "The figures you enter into any calculator — loan amounts, salaries, deposits, dates — are worked out on your phone and are never sent to us. We record only that a calculator was opened.",
      "We never receive your Google password.",
    ],
    terms: {
      updated: "September 6, 2026",
      intro:
        "These terms apply to the BankMates app and cover the things a general terms page cannot: what its calculators are and are not, what the coaching content is, and what may and may not be posted in a space shared with your colleagues. Where they differ from our general terms of service, these take precedence for BankMates.",
      sections: [
        {
          heading: "Who may use BankMates",
          body: [
            "You must be at least 18 and an employee, retired employee, or trainee of a bank or financial institution in India. You identify your own employer during sign-up; we do not verify it with your bank, and you must not claim to work somewhere you do not.",
            "Your account is yours alone. Do not share your sign-in with anyone, including a colleague.",
          ],
        },
        {
          heading: "Calculator results are estimates, not your bank's figures",
          body: [
            "Every calculator in BankMates is an independent illustration. It is **not** a quotation, sanction, statement of account, or any other official figure, and it does not come from your bank or from any bank.",
            "Interest conventions differ between institutions and between products — rounding, day-count, the balance a month's interest is charged on, when a rate reset applies. We have implemented the conventions described in the app, and we state them on each screen so you can check them. Your employer's own system is the authority on what any borrower or depositor actually owes or receives.",
            "Do not use a BankMates figure to quote a rate to a customer, to answer a customer's query about their own account, or in any document that leaves your branch. Check it against your core banking system first.",
            "We are not liable for any loss arising from reliance on a calculator output.",
          ],
        },
        {
          heading: "The SARFAESI timeline tool in particular",
          body: [
            "The SARFAESI screen projects dates from statutory periods that are printed on screen with the section or rule each comes from. Those periods are shown so you can verify them; they are **not** legal advice and have not been settled by counsel for this app.",
            "Every period is editable precisely because you should not accept ours without checking. A recovery action taken on a wrong date can be set aside. Confirm each date against the Act, the current rules, any applicable court direction, and your bank's own recovery policy before acting.",
          ],
        },
        {
          heading: "Coaching content",
          body: [
            "The JAIIB and CAIIB material in BankMates is independent study material. We are **not** affiliated with, endorsed by, or connected to the Indian Institute of Banking and Finance, and BankMates is not an official IIBF study resource. JAIIB, CAIIB and IIBF are the marks of their respective owners and are used here only to describe what the material covers.",
            "Chapters marked as drafts are unfinished and should not be relied on for an examination. The syllabus is set by IIBF and changes; check the current syllabus on their site before you sit a paper.",
            "We do not promise that using BankMates will help you pass anything.",
          ],
        },
        {
          heading: "Your bank's circle, and what must not be posted",
          body: [
            "Doubts, tips and messages are visible to other BankMates users who have identified the same employer as you. Treat that as a staffroom conversation among people you have not met, because that is what it is — we do not verify anyone's employment.",
            "You must **not** post customer or borrower information of any kind. That includes names, account numbers, loan account numbers, CIF or customer IDs, PAN, Aadhaar, balances, transaction details, contact details, and any document or screenshot containing them. Ask your question in general terms.",
            "You must also not post anything your employer classifies as confidential or internal — unreleased circulars, internal audit findings, security procedures, credentials, or system screenshots.",
            "Your bank's own service conduct rules, IT policy and confidentiality obligations continue to apply to what you write here. Nothing in BankMates overrides them, and we cannot shield you from the consequences of breaching them.",
            "Also out of bounds: harassment, abuse, communal or casteist content, content targeting a colleague, spam, recruitment or sales pitches, and anything unlawful.",
          ],
        },
        {
          heading: "Content you post",
          body: [
            "You keep ownership of what you write. You give us permission to store it and show it to colleagues at your bank so the app can work, and to keep a copy briefly after deletion so a report against it can be reviewed.",
            "Anyone can report a post. We may hide or remove content, and suspend or close an account, where a post breaks these terms — including where it exposes customer information, which we will act on quickly and without waiting for a report.",
            "Tips can be posted by users who identify themselves as officers or executives. That is a self-declared field, not something we verify, and a tip carries no authority beyond the person who wrote it.",
            "Advice from a colleague is a colleague's opinion. It is not your bank's position, and it is not ours.",
          ],
        },
        {
          heading: "Invitations",
          body: [
            "Only invite people you know and who would expect to hear from you. Each address receives one invitation and no reminders.",
            "Do not enter addresses from a customer list, a directory, or anywhere else you have not been given the address personally. Accounts used to send bulk or unsolicited invitations will be closed.",
          ],
        },
        {
          heading: "Availability, and ending your account",
          body: [
            "BankMates is provided as it is. We do not guarantee it will be available without interruption, and we may change or withdraw features. The calculators are designed to keep working offline; the rest of the app needs a connection.",
            "You can delete your account at any time — see the account deletion page. We may suspend or close an account that breaks these terms, and will tell you why unless we are prevented from doing so.",
          ],
        },
        {
          heading: "Liability",
          body: [
            "To the extent the law allows, we are not liable for indirect or consequential loss, for loss of profit or opportunity, or for any loss arising from reliance on a calculator output, on coaching content, or on advice given by another user.",
            "Nothing here limits liability that cannot be limited by law.",
          ],
        },
        {
          heading: "Governing law",
          body: [
            "These terms are governed by the laws of India, and the courts at Kozhikode, Kerala have jurisdiction.",
          ],
        },
      ],
    },
  },
  {
    tagline: "Revise. Recall. Rank.",
    audience:
      "Candidates preparing for Kerala Public Service Commission examinations. Anyone can create an account with a Google account.",
    summary:
      "Recallio teaches a PSC syllabus as small fact cards and schedules them with spaced repetition, so each fact comes back just before you would have forgotten it. A day takes about five minutes, and the plan is counted back from your exam date.",
    collects: [
      {
        category: "Personal identifiers",
        items: ["Name", "Email address", "Profile picture"],
        purpose:
          "Creating your account and recognising you when you sign in on another phone. All three come from Google Sign-In; we never see your Google password.",
      },
      {
        category: "App activity",
        items: [
          "Which course you are preparing for, your exam date and when your plan started",
          "Which cards you have been shown, whether you answered each correctly, how many times, and when each is next due",
          "Mock test attempts: the option you chose for each question, and the resulting score",
          "Your daily reminder time and whether you chose English or Malayalam",
        ],
        purpose:
          "This is the study record itself. The schedule is computed from it, and it is what makes a streak, a progress bar and a weak-module figure possible. It is also what would be lost if it were not backed up, which is why it is stored to your account and not only on the phone.",
      },
      {
        category: "Purchases",
        items: ["Whether a subscription for a course is active", "Which payment route was used"],
        purpose:
          "Unlocking the course you paid for, and restoring it after a reinstall. The payment itself is handled entirely by Google Play or by Razorpay — we never see your card, UPI or netbanking details.",
        optional: true,
      },
      {
        category: "Device identifiers",
        items: ["Push notification token"],
        purpose:
          "Delivering announcements that only a server can know about — a corrected card, new material for your course, a payment that completed while the app was closed. Your daily study reminder does NOT use this: that one is scheduled by your own phone and needs no token. Sign out and the token is deleted.",
        optional: true,
      },
    ],
    permissions: [
      {
        name: "Notifications",
        why: "Two separate things share this permission. Your daily study reminder is scheduled by your own phone at the time you chose, needs no token and arrives with no signal. Announcements — corrected cards, new material — are sent from our server and do use a push token, which you can stop by turning notifications off.",
      },
      {
        name: "Internet",
        why: "Signing in, downloading course content, and backing up your study record. The app is built to work without it: once content has been downloaded, a full day's study works with no signal.",
      },
    ],
    sharedWith: [],
    processors: ["google", "supabase", "play_billing", "razorpay_recallio", "fcm"],
    retention:
      "Your study record is kept while your account exists, because its value is that it remembers years of revision. Delete the account and it is removed within 30 days. Content you never touched — the cards themselves — is ours and is not personal data.",
    iconSrc: "/recallio/icon.png",
    qr: {
      svg: "/recallio/qr.svg",
      png: "/recallio/qr.png",
      target: "https://calecutech.com/apps/recallio",
    },
    availabilityNote:
      "Recallio is not on Google Play yet. This page carries the store link once the listing is live, and it is already the address printed on anything we hand out, so nothing has to be reprinted later.",
    features: [
      "The official syllabus broken into small fact cards — a statement, why it is true, the trick the exam plays with it, and where it comes from.",
      "Spaced repetition tuned for an exam date: every interval is capped so nothing is ever scheduled after the day you sit the paper, and every card is shown at least once in the final ten days.",
      "A 100-day plan derived from the marks each module carries, not from guesswork — coverage, then consolidation, then final revision on the cards you have actually got wrong.",
      "Miss a day and the backlog is spread across the next three rather than dumped on tomorrow. Miss a week and the plan is rebuilt from the days that actually remain.",
      "Negative marking is shown wherever a score appears, taken from the course itself rather than assumed — skipping costs nothing, guessing does.",
      "Every card in both English and Malayalam, with technical terms left in English because that is how the exam writes them.",
      "Works offline. Study data lives on the phone first and syncs when there is a connection, so a day on patchy mobile data is still a day of study.",
    ],
    policyUpdated: "September 17, 2026",
    serviceName: "the Recallio service",
    lawfulBasis:
      "We process your data to provide the service you asked for — an account, a study plan, and a record of what you have revised. You give consent when you create an account, and you may withdraw it at any time by deleting the account.",
    signInHelp:
      "Recallio uses Google Sign-In only, and there is no guest mode — your progress has to belong to an account or a new phone could not restore it. If sign-in fails, check that the Google account has a verified email address. We cannot reset a Google password; that is done at myaccount.google.com. If a subscription does not appear after reinstalling, open Papers and tap Restore, and make sure you are signed in with the same Google account that bought it.",
    securityNote:
      "Every table is protected by a database policy that ties a row to the account that owns it, so one signed-in user cannot read another's study record even if the app on their phone is tampered with. Sign-in tokens are held in the Android keystore or iOS keychain, never in ordinary app storage.",
    deleteIdentifier: "the Google account you sign in with",
    deletes: [
      "Your name, email address and profile picture",
      "Your course, exam date, plan start date, reminder time and language",
      "Your entire study record — every card's schedule, your streak, and how many times you have seen each fact",
      "Every mock test attempt and its score",
      "Your push notification token, so this device stops receiving anything",
      "Any active sessions",
    ],
    retainsOnDelete:
      "Nothing identifying you is kept. A subscription is a record held by Google Play or Razorpay, not by us, so deleting your Recallio account does **not** cancel it — cancel that in the Play Store, or it will keep renewing. Deleting your account does not refund a subscription already paid for.",
    notCollected: [
      "We do not collect your contacts, calendar, call logs or SMS.",
      "We do not track you across other apps or websites, and there is no analytics or advertising SDK in the app.",
      "We do not use advertising identifiers and show no advertising.",
      "The app never asks for camera, microphone, location or file access, because it does not use them.",
      "We never receive your Google password, and never your card, UPI or netbanking details — those are entered on Google Play's or Razorpay's own screen.",
    ],
    terms: {
      updated: "September 17, 2026",
      intro:
        "These terms apply to the Recallio app and cover what a general terms page cannot: what the study material is and is not, who sets the syllabus, and how subscriptions bought through Google Play work. Where they differ from our general terms of service, these take precedence for Recallio.",
      sections: [
        {
          heading: "Recallio is not connected to the Kerala PSC",
          body: [
            "Recallio is an independent study app made by Calecute Technologies LLC. We are **not** affiliated with, endorsed by, appointed by, or connected in any way to the Kerala Public Service Commission or to any government department of the State of Kerala or the Union of India.",
            "\"Kerala PSC\", category numbers, post names and syllabus titles are used only to describe what the study material covers. We do not conduct examinations, issue notifications, accept applications, or influence any recruitment decision. Nobody at Recallio can help with your application, your hall ticket, your rank list, or any grievance about them — those go to the Commission.",
            "The Commission's own notification is the only authority on the syllabus, the exam pattern, the marks, the negative marking and the dates. Where anything in this app differs from it, the notification is right and we are wrong. Check it before you rely on us.",
          ],
        },
        {
          heading: "The study material",
          body: [
            "Cards are written and checked by people, and people make mistakes. A card marked as unverified has not yet been checked against the source named on it. Even a verified card can be wrong, out of date, or overtaken by a change in the syllabus.",
            "Where we reproduce a past question, the official answer key is shown as published. Where our review disagrees with that key we say so and show both — but the Commission's key is what was used to mark that paper, whatever we think of it.",
            "The Malayalam text is a translation for study. Technical terms are deliberately left in English because that is how the exam and the standard textbooks write them.",
            "Report anything that looks wrong and we will check it. Corrections reach the app without you needing to update it.",
          ],
        },
        {
          heading: "We do not promise you a rank",
          body: [
            "The tagline is what the method is for, not a guarantee of outcome. Nothing in this app is a promise that you will pass, be shortlisted, place in a rank list, or be appointed.",
            "A daily plan, a streak and a progress figure describe what you have revised in this app. They do not measure how prepared you are, and they do not predict your result.",
            "We are not liable for any loss arising from reliance on the study material, a mock test score, or anything else in the app.",
          ],
        },
        {
          heading: "Free cards and subscriptions",
          body: [
            "The first 200 cards of a course are free, and they are ordinary cards taken in teaching order from the start of the syllabus — not a sample or a teaser. They exist so you can judge the method before paying for it.",
            "After that, a course needs a subscription. What it unlocks is stated on the paywall before you pay: every card for that course, scheduled day by day through to your exam date.",
            "If you do not subscribe you keep your account, your streak, your progress on those first 200 cards, and read-only access to the plan. We do not delete a free user's data and we do not reset a streak.",
          ],
        },
        {
          heading: "Payment, renewal and refunds",
          body: [
            "You can pay through Google Play or by UPI or card through Razorpay. Where you pay through Google Play, Google is the merchant of record and the price shown comes from Google Play including any tax it collects. Where you pay by UPI or card, the price is the one shown in the app and Calecute Technologies LLC is the merchant of record.",
            "A subscription renews automatically until you cancel it, and deleting your Recallio account does not cancel it. **A Google Play subscription is cancelled in the Play Store.** A UPI or card subscription is cancelled by writing to us, and we will stop the renewal.",
            "A Google Play purchase follows Google Play's refund policy and is requested through Google, not through us — we cannot reverse a Play charge ourselves. A UPI or card payment is refunded by us under our refund policy; write to us and we will process it back to the same method.",
            "A subscription is tied to your Recallio account, however you paid. Reinstalling or moving to a new phone restores it — sign in with the same Google account, and tap Restore on the Papers screen if you paid through Google Play. You should never need to contact us to get back something you paid for.",
          ],
        },
        {
          heading: "Your account and your study record",
          body: [
            "Sign-in is required before the first card, because a study record that is not tied to an account cannot survive a lost phone.",
            "Your account is yours alone. Do not share your sign-in, and do not share subscription access with others.",
            "Your study record belongs to you. It is stored on your phone first and copied to your account, and where the two disagree the phone wins — we would rather keep a day of study you have already done than a tidier copy on a server.",
            "You can delete your account at any time; see the account deletion page. We may suspend an account that is being shared, automated, or used to extract the content in bulk.",
          ],
        },
        {
          heading: "The content itself",
          body: [
            "The cards, questions, explanations and translations in Recallio are our work and remain ours. You may use them to study. You may not copy, republish, sell, or feed them into another product or service, and you may not scrape the app.",
            "Past examination questions belong to the Commission that set them and are reproduced for study.",
          ],
        },
        {
          heading: "Availability",
          body: [
            "Recallio is provided as it is. We do not guarantee it will be available without interruption, and we may change or withdraw features.",
            "The app is built to work offline once content has been downloaded, and a day of study does not need a connection. Signing in, downloading a new course and backing up your progress do.",
            "Reminders are scheduled by your phone. If the phone is off, or the system stops the app to save battery, a reminder may not arrive. Your streak is not a promise that we will remind you.",
          ],
        },
        {
          heading: "Liability",
          body: [
            "To the extent the law allows, we are not liable for indirect or consequential loss, for loss of profit or opportunity, or for any loss arising from reliance on the study material, a mock score, an exam date, or a schedule.",
            "Nothing here limits liability that cannot be limited by law.",
          ],
        },
        {
          heading: "Governing law",
          body: [
            "These terms are governed by the laws of India, and the courts at Kozhikode, Kerala have jurisdiction.",
          ],
        },
      ],
    },
  },
];

/**
 * Demo and production are separate published apps, not one app promoted.
 *
 * The demonstration builds are shown to banks and used for staff training
 * indefinitely, so they must install alongside production rather than replace
 * it. That means separate package ids, separate store listings, and separate
 * OAuth clients — and therefore separate policy pages, since Google matches
 * the app name on the consent screen against the one on this page.
 */
const FIELD = 0;
const BUYER = 1;
const BANKMATES = 2;
const RECALLIO = 3;

export const APPS: AppEntry[] = [
  {
    ...BASE[FIELD],
    slug: "sarfez-field-demo",
    name: "Sarfez Field Demo",
    androidPackage: "com.calecutech.sarfez.demo.field",
    iosBundleId: "com.calecutech.sarfez.demo.field",
    isDemo: true,
  },
  {
    ...BASE[FIELD],
    slug: "sarfez-field",
    name: "Sarfez Field",
    androidPackage: "com.calecutech.sarfez.live.field",
    iosBundleId: "com.calecutech.sarfez.live.field",
    isDemo: false,
  },
  {
    ...BASE[BUYER],
    slug: "sarfez-auctions-demo",
    name: "Sarfez Auctions Demo",
    androidPackage: "com.calecutech.sarfez.demo.buyer",
    iosBundleId: "com.calecutech.sarfez.demo.buyer",
    isDemo: true,
  },
  {
    ...BASE[BUYER],
    slug: "sarfez-auctions",
    name: "Sarfez Auctions",
    androidPackage: "com.calecutech.sarfez.live.buyer",
    iosBundleId: "com.calecutech.sarfez.live.buyer",
    isDemo: false,
  },
  {
    ...BASE[BANKMATES],
    slug: "bankmates",
    name: "BankMates",
    androidPackage: "com.calecutech.bankmates",
    iosBundleId: "com.calecutech.bankmates",
    isDemo: false,
  },
  {
    ...BASE[RECALLIO],
    slug: "recallio",
    name: "Recallio",
    androidPackage: "com.calecutech.recallio",
    iosBundleId: "com.calecutech.recallio",
    isDemo: false,
  },
];

export function appBySlug(slug: string): AppEntry | undefined {
  return APPS.find((a) => a.slug === slug);
}
